### ISSUE TITLE
confluent cli fails to create machine-id file 

### ISSUE THREAD

**Issue by akila-tmr** [confluentinc/cli#1799]
I'm trying to deploy the confluent-cli pod into an EKS cluster with OPA Gatekeeper. It has an OPA constraint that enforces `readOnlyRootFilesystem`. Therefore, we must set the `readOnlyRootFilesystem: true` to comply with the OPA constraint. 

However, it prevents writing to the pod's `/etc` folder. When we run the `confluent login --no-browser`, it doesn't create the `/etc/machine-id`. 
 Hence, we get the following error after a successful login.

`cipher: message authentication failed`.

Is storing the `machine-id` in the confluent user home (`/home/confluent`) possible?

**Comment by MuweiHe** [comment]
Except for Alpine, cli doesn't store the machine id but directly read them from `/etc/machine-id`. Alpine doesn't have this file. So I assume you're running on Alpine system. I'll look into this issue and get back to you.

**Comment by akila-tmr** [comment]
Yeah, its an Alpine image.

**Comment by MuweiHe** [comment]
@akila-tmr will you be able to generate a machine id to that dir, and then set it to read-only? follow the steps here: https://github.com/automation-stack/node-machine-id/issues/4#issuecomment-262486192 and generate the id to either `/var/lib/dbus/machine-id`, `/etc/machine-id`, then cli only need read access to get the id.

**Comment by MuweiHe** [comment]
In the meantime, you can try cli versions earlier than 3.2.0, which don't have the encryption features.

**Comment by MuweiHe** [comment]
Closing this issue as no new replies
