### ISSUE TITLE
'confluent local services start' not longer working

### ISSUE THREAD

**Issue by andhusa** [confluentinc/cli#1960]
The command `confluent local services start` is not working anymore. Is there anything else we are supposed to use?

**Comment by brianstrauch** [comment]
In [v3.16.0](https://docs.confluent.io/confluent-cli/current/release-notes.html#confluent-cli-v3-16-0-release-notes), we released an improved Docker-based version of `confluent local`. If it's missing any functionality you need, you can still download an older version of the CLI to use the old Java-based `confluent local` command!
