### ISSUE TITLE
General questions about `confluent local kafka start`

### ISSUE THREAD

**Issue by Pontius1007** [confluentinc/cli#1963]
Hello, 

I have a few general remarks and questions in regard to the docker version for what used to be `confluent local services start`. 

From my understanding of previous use, the bootstrap servers have been default available at localhost:9092. From the logged KafkaRestConfig I can see that: `bootstrap.servers = broker:44535`. Is this documented somewhere or is it expected from the users that we manually check the KafkaRestConfig? 

We have our local development environment running in Docker Containers, and needed to manually get the `docker run` command and modify it with the `--net` flag to facilitate communication. Is there any plan to support additional configuration to avoid this issue? 

This enabled us to get a connection with the bootstrap servers at broker:44535, but we fail to get a response from the Schema Registry which we would expect to be available at `http://localhost:8081`. Any idea why? 

Additionally, we do not get any feedback in the terminal when running `confluent local kafka start`. You are left with a blank terminal until the image is finished downloading, and I miss the printed output previously available as:
`
Starting Zookeeper
Zookeeper is [UP]
Starting Kafka
Kafka is [UP]
Starting Schema Registry
Schema Registry is [UP]
Starting Kafka REST
Kafka REST is [UP]
Starting Connect
Connect is [UP]
Starting KSQL Server
KSQL Server is [UP]
Starting Control Center
Control Center is [UP]
`

And it sometimes fail to create a docker container when running "confluent local kafka start`, and multiple retries are needed without any console output. 

I do also believe that this documentation: https://docs.confluent.io/platform/6.2/quickstart/ce-quickstart.html is outdated after the 3.16 release. 

Thanks in advance! 

BR

**Comment by Pontius1007** [comment]
Hello! 

First of all, thanks for the fast reply and the in-depth answer. 

I do believe that would help! I am not sure how easy it would be, but would it be possible to take in additional configuration via the `--build-args` variable? https://docs.docker.com/engine/reference/commandline/build/#build-arg 

I did some more testing and I guess the "fail to start" was mostly me getting impatiant with the no output and manually disabling the job, which was downloading in the background. Some output on the download progress would be greatly appreciated! 

Hopefully my last message didn't scare you too much!

**Comment by MuweiHe** [comment]
Hi!

It makes sense to me to use default ports if user doesn't specify config! Will try to follow the old convention and will include it in this week's minor release!
