### ISSUE TITLE
Couldnt install

### ISSUE THREAD

**Issue by jainal09** [confluentinc/cli#2041]
Os ubuntu 22 64 bit
I am getting the below msg when I tried installing the latest
```
❯ curl -sL --http1.1 https://cnfl.io/cli | sh -s -- latest
confluentinc/cli info checking S3 for tag 'latest'- latest
confluentinc/cli crit unable to find 'latest' - use 'latest' or see https://docs.confluent.io/confluent-cli/current/release-notes.html for available versions.
```

Even installing 3.6.0 gives me the below error
```
❯ curl -sL https://raw.githubusercontent.com/confluentinc/cli/main/install.sh | sh -s -- -b /usr/local/bin 3.6.0
confluentinc/cli info checking S3 for tag '3.6.0'luentinc/cli/main/install.sh | sh -s -- -b /usr/local/bin 3.6.0
confluentinc/cli crit unable to find '3.6.0' - use 'latest' or see https://docs.confluent.io/confluent-cli/current/release-notes.html for available versions.
```

**Comment by MuweiHe** [comment]
currently our latest should be v3.25.0. are you still seeing this issue happening? `curl -sL --http1.1 https://cnfl.io/cli | sh -s -- latest` should give you the latest version, or you can consider checking if your have firewall preventing you from accessing s3

**Comment by brianstrauch** [comment]
I'd recommend following the second step from https://github.com/confluentinc/cli#scripted-installation:
```
curl -sL https://raw.githubusercontent.com/confluentinc/cli/main/install.sh | sh -s -- -l
```

If this doesn't print a list of CLI versions, you may have a connection issue as @MuweiHe suggested. You can also try downloading from the "Releases" tab on GitHub, or with `brew install confluentinc/tap/cli`.

**Comment by brianstrauch** [comment]
Closing as this is over a month old. Please open a new issue if the above does not resolve your issue @jainal09
