### ISSUE TITLE
How to define Kafka storage path on Confluent CLI

### ISSUE THREAD

**Issue by AAlex-11** [confluentinc/cli#2094]
I have simple local installation [docs.confluent.io/platform/current/installation/installing_cp/…](https://docs.confluent.io/platform/current/installation/installing_cp/zip-tar.html) and it working perfectly, but important parameters can not changed.

I use standard home path for confluent center

       export CONFLUENT_HOME=/home/kafka/confluent/confluent-7.4.0

Unfortunately, I can not change path to store data. I found Kafka config in path and set up needed storage

      cat /home/kafka/confluent/confluent-7.4.0/etc/kafka/server.properties | grep log.dir
      log.dirs=/storage/kafka-logs

Than I restart Confluent Platform, however Path is wrong

     ./confluent local services start
     The local commands are intended for a single-node development environment only, NOT for production usage. See more: https://docs.confluent.io/current/cli/index.html
     As of Confluent Platform 8.0, Java 8 is no longer supported.

     Using CONFLUENT_CURRENT: /tmp/confluent.430818
     Starting ZooKeeper
     ZooKeeper is [UP]
     Kafka is [UP]
     Starting Schema Registry
     Schema Registry is [UP]
     Starting Kafka REST
     Kafka REST is [UP]
     Starting Connect
     Connect is [UP]
     Starting ksqlDB Server
     ksqlDB Server is [UP]
     Starting Control Center
     Control Center is [UP]

I try to use Clonfluent CLI to change path to store data, but not found this parameter.  I try to use 

    ./ confluent context list 

in order to update and receive answer - Context None found. 
Second possible to manage default setting 

    ./confluent kafka acl list

answer is Error: Kafka REST URL not found, but in reality REST API found

![wbMx5](https://github.com/confluentinc/cli/assets/138773344/f6d35225-0b02-4f7c-9030-867aa4484eb8)

If I try to use

      ./confluent kafka topic list 

give me "No session token found, please enter user credentials. To avoid being prompted, run "confluent login". - login to what? Login to confluent cloud need credit card firstly, even to free plan. What this is trash? To change configuration on my local installation I must set up my credit card to Confluent company? Or what login means this command line?

**Comment by MuweiHe** [comment]
`./confluent kafka topic list ` this is a cloud command and not supported for cp cli, that's why it prompt for login.
Can you try install cli directly via `curl -sL --http1.1 https://cnfl.io/cli | sh -s -- latest` and see if that fixes the issue?
also please notice that this is the old `confluent local` commands and should be deprecated. We encourage you to try the new confluent local experience by running `confluent local kafka start` in latest cli versions.

**Comment by AAlex-11** [comment]
I'm sorry, I refuse to use Kafka in any my project (because nobody can answer to any question and support is absent at all), unfortunately I can not check this recipe.
