### ISSUE TITLE
confluent kafaka client-config is broken 

### ISSUE THREAD

**Issue by mirwisek** [confluentinc/cli#2145]
I'm following the Kafka-Connect-101 (https://developer.confluent.io/courses/kafka-connect/connect-api-hands-on/) and I can't figure out what's wrong with the following:
Command 14 at tutorial:
```
confluent kafka client-config create java --sr-apikey <sr API key> --sr-apisecret <sr API secret> | tee $HOME/.confluent/java.config
```
The script is outdated since the documentation here has changed `--sr-apikey` to full form and they are not consistent (https://docs.confluent.io/confluent-cli/current/command-reference/kafka/client-config/create/confluent_kafka_client-config_create_java.html)
I'm basically getting command not found for client-config, I couldn't find any information on whether the API has been moved since the documentation still says it's the same.

VERSION: **confluent-7.1.1**

```
3456253:~# confluent kafka client-config
Manage Apache Kafka.

Usage:
  confluent kafka [command]

Available Commands:
  acl            Manage Kafka ACLs.
  cluster        Manage Kafka clusters.
  link           Manages inter-cluster links.
  mirror         Manages cluster linking mirror topics.
  region         Manage Confluent Cloud regions.
  topic          Manage Kafka topics.

Global Flags:
  -h, --help            Show help for this command.
  -v, --verbose count   Increase verbosity (-v for warn, -vv for info, -vvv for debug, -vvvv for trace).

Use "confluent kafka [command] --help" for more information about a command.
```

**Comment by brianstrauch** [comment]
We'll update the documentation right away, thank you!

Regarding the missing `confluent kafka client-config` command, it looks like you're using `confluent` v2.6.1 (according to [this table](https://docs.confluent.io/platform/current/installation/versions-interoperability.html#confluent-cli), that's the version that's shipped with Confluent Platform 7.1) but that command was added in `confluent` v2.7.0: https://docs.confluent.io/confluent-cli/current/release-notes.html#confluent-cli-v2-7-0-release-notes

I'd recommend updating your version of Confluent Platform, or installing the CLI separately (via `curl` or `brew`).
