### ISSUE TITLE
Errors with the Windows version

### ISSUE THREAD

**Issue by lbcommer** [confluentinc/cli#2159]
I think there may be a bug in Confluent CLI for Windows: I installed the last available version (file confluent_3.25.1_windows_amd64.zip), and It works ok for some orders (getting the list of topics from the cluster, creating a topic), so connectivity and credentials are ok, but I get an error trying to read from an existing topic with `confluent kafka topic consume -b my-topic`:

%3|1691140847.189|FAIL|Confluent-CLI_v3.25.1#consumer-1| [thrd:sasl_ssl://pkc-1wvvj.westeurope.azure.confluent.cloud:9092/boot]: sasl_ssl://pkc-1wvvj.westeurope.azure.confluent.cloud:9092/bootstrap: SASL authentication error: Authentication failed (after 5283ms in state AUTH_REQ)

From Linux, I don't get this error.

**Comment by lbcommer** [comment]
I've just seen there is a new version (3.26). I have applied the update but still see the same error.

**Comment by sgagniere** [comment]
We're looking into it.

In the meantime, v3.18.0 should work.
