### ISSUE TITLE
confluent kafka topic produce/consume misbehaving for integers

### ISSUE THREAD

**Issue by natalia-ramos-bzy** [confluentinc/cli#2232]
Cannot produce integer keys with confluent cli version v3.30.1

Steps to reproduce:
1. Init the producer with integer key and string value
`confluent kafka topic produce test.integers --key-format integer --value-format string --parse-key
`
2. Send a record:
`1:Test`

3. Init the consumer and receive a wrong key:
`confluent kafka topic consume test.integers --key-format integer --value-format string --print-key --from-beginning
`![image](https://github.com/confluentinc/cli/assets/138798746/e06b8ead-c45a-40c1-b8f8-23c70f93ac51)

**Comment by sgagniere** [comment]
A fix for this issue will be included in our next release.
