### ISSUE TITLE
Produce to topic with avro key schema results in an error

### ISSUE THREAD

**Issue by natalia-ramos-bzy** [confluentinc/cli#2265]
I have a topic with a simple avro schemas for key and value
Key schema:
```
{
  "fields": [
    {
      "name": "CustomerId",
      "type": "int"
    }
  ],
  "name": "CustomerKey",
  "type": "record"
}
```
Value schema:
```
{
  "fields": [
    {
      "name": "FirstName",
      "type": "string"
    },
    {
      "name": "LastName",
      "type": "string"
    }
  ],
  "name": "CustomerValue",
  "type": "record"
}
```
When trying to produce to the topic, I get an error:
```
confluent kafka topic produce <topic> --key-format avro --value-format avro --schema <value-schema-id> --key-schema <key-schema-id> --parse-key
{"CustomerId": 1}:{ "FirstName": "Maria", "LastName": "Garcia"}
```
The error reads:
`Error: cannot decode textual record ... : short buffer
`

**Comment by sgagniere** [comment]
This is happening because the CLI parses the first `:` inside the key as the delimiter, instead of the `:` between the key and the value.

We're working on it, but in the meantime you can try using a different delimiter by passing the `--delimiter` flag to `produce`.
