### ISSUE TITLE
Launching confluent local kafka start fails with Error: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by mcascallares** [confluentinc/cli#2271]
When launching 'confluent local kafka start', I get this error:

```
confluent local -vvvv kafka start
The local commands are intended for a single-node development environment only, NOT for production usage. See more: https://docs.confluent.io/current/cli/index.html


Pulling from confluentinc/confluent-local
Digest: sha256:8e391de42cfcd3498e7317dcf159790f1f1cc3f3ffce900b30d7da23888687fd
Status: Image is up to date for confluentinc/confluent-local:latest
2023-09-19T10:04:18.214+0200 [TRACE] Successfully pulled Confluent Local image
Error: runtime error: index out of range [0] with length 0
```

Find below my CLI information

```
confluent - Confluent CLI

Version:     v3.33.0
Git Ref:     53da89b2
Build Date:  2023-09-14T22:43:04Z
Go Version:  go1.21.0 X:boringcrypto (darwin/amd64)
Development: false

```
Find below my docker environment information

```
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 59
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.3.13-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.769GiB
 Name: docker-desktop
 ID: 746e542e-f404-4449-b366-ba2a54e391a8
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

**Comment by mcascallares** [comment]
Executing the same image "manually" works

`docker run --name confluent-local -d -p 9092:9092 -p 8082:8082 -p 29092:29093 confluentinc/confluent-local`

**Comment by MuweiHe** [comment]
Might be an issue with setting up ports to use in confluent local. can you reproduce the state of error and share with me the content of ~/.confluent/config.json, the part close to the end of file where it says local_ports? e.g.
```
"local_ports": {
    "broker_ports": [
      "53229"
    ],
    "controller_ports": [
      "53230"
    ],
    "kafka_rest_port": "8082",
    "plaintext_ports": [
      "53228"
    ]
  }
```
And if they're not empty, can you check if any of those 4 ports are bind with other processes?

**Comment by MuweiHe** [comment]
Thanks! Looks like CLI failed to assign a free port to broker ports etc.
Does running `confluent local kafka start --brokers 1~4` (specifying the number of brokers) work for you?

**Comment by MuweiHe** [comment]
Although editing the file after running `start` would not work, as those values should be configured before starting the container.

**Comment by MuweiHe** [comment]
Other possible items you could look into: the `freeport` package tries to identify free ports by binding to a port number of 0 (which lets the OS pick a free port) and then immediately releasing it. If there're concurrent Go applications running / firewall or network settings like in a container or cloud setup, the process of detecting free ports might fail.

**Comment by MuweiHe** [comment]
Hi @mcascallares Do you still see `Error: Error response from daemon: Ports are not available: exposing port TCP localhost:8082 -> 0.0.0.0:0: listen tcp: lookup <nil>: no such host`? One temp relief is to downgrade docker to 4.22.0 or earlier while i investigate further

**Comment by mcascallares** [comment]
Hi @MuweiHe! Thanks for reaching out.

I tested it disabling GlobalProtect, no existing Docker containers, and still the same issue. The workaround that you mentioned, using Docker 4.22.0 earlier, does make sense since used to work before, but I haven't tested it yet.

**Comment by MuweiHe** [comment]
Hi @mcascallares i have included a fix for this issue in today's release (should be v3.41.0). turned out new docker have stopped auto mapping `localhost` to `0.0.0.0` by looking up in etc/hosts, so i needed to explicitly declare a `0.0.0.0` host. Can you help verify v.3.41.0 works for you or not? thanks!
(the release should be out later today

**Comment by mcascallares** [comment]
Hi @MuweiHe 
I just updated the confluent CLI and worked perfectly. 

Thank you so much!
