### ISSUE TITLE
Support linux/arm64 in the Confluent Platform package

### ISSUE THREAD

**Issue by tsegars-efx** [confluentinc/cli#2453]
I have installed Confluent Platform 7.5.2 per the [Install Confluent Platform using Systemd on RHEL and CentOS](https://install/ Confluent Platform using Systemd on RHEL and CentOS) page. I’m installing on Amazon Linux 2023 AWS instance. I’ve completed all steps up to 
     “Test that you set the CONFLUENT_HOME variable correctly by running the confluent command: confluent --help”. 
 When I run confluent --help, I get the following error:
 
confluentinc/cli crit platform linux/arm64 is not supported. **Make sure this script is up-to-date and file request at [Sign in to GitHub · GitHub](https://github.com/confluentinc/cli/issues/new)**

As I just extracted the Confluent from the confluent-7.5.2.tar.gz tarball, I believe the script should be up-to-date. Can anyone provide some direction on how I might correct this situation?

**Comment by brianstrauch** [comment]
Hi, linux/arm64 is not supported in Confluent Platform yet, but it _is_ supported in the independent CLI release channel. Please download the CLI following the instructions here and let us know if you run into any other problems: https://github.com/confluentinc/cli?tab=readme-ov-file#scripted-installation

**Comment by sgagniere** [comment]
Linux arm64 should now be available in all versions after (and including) 7.5.4.
