### ISSUE TITLE
Schema API Keys Result in 401

### ISSUE THREAD

**Issue by dangoslen** [confluentinc/cli#2508]
I recently just upgraded from 3.38 to 3.45. 

Using the `confluent kafka topic consume` command, when specifying details for Schema Registry API Key/secret and endpoint, I get a 401 with an API key I have been using before without error.

Concretely I get the following error output
```
Starting Kafka Consumer. Use Ctrl-C to exit.
Error: failed to validate Schema Registry client: 401 Unauthorized
```

I imagine the same bug exists for `produce` as well.

**Comment by MuweiHe** [comment]
Hi @dangoslen ! I'm on CLI v3.45 but failed to reproduce the issue. my steps:

- remove config.json
- login to cli
- create a new pair of kafka api-key and use it for the kafka cluster
- consume from a topic using a pre-existing schema registry api-key
- successfully consumed from the topic with schema specified

To help us further debug the issue you're seeing, please provide your steps as detailed as possible, including the commands you used. thanks!

**Comment by dangoslen** [comment]
Hi @MuweiHe! Thanks for taking a look.

Interesting finding. I'm wondering if perhaps I didn't have a proper API key setup and there was some fallback logic to run as my logged in Confluent account. It was just a confusing experience.

Happy to close this out. Thanks for looking.
