### ISSUE TITLE
Consuming While Producing Fails

### ISSUE THREAD

**Issue by dangoslen** [confluentinc/cli#2519]
Hi again.

I'm seeing an odd error when attempting to have both a consumer and producer using the CLI running at the same time.

I start a consumer using the `confluent kafka topic consume` command. I'm using an avro schema that is configured already on the topic via the Schema Registry in Confluent Cloud.

I think go to a new terminal to create a producer using the `confluent kafka topic produce` command. I'm sending the raw Avro schema (.avsc file). I successfully produce the message (and I see it produced properly in Confluent Cloud).

However, the `consumer` now breaks. I get the following error (which is from the golang stdlib)

```bash
Error: open /<temp-directory>/ccloud-schema/<topic-name>-<registered-schema-id>.txt: no such file or directory
```

Interestingly, if I restart the consumer and use the `--from-begginning` option, I successfully get the message

I'm wondering if there is some attempt at an optimization to cache the registered schema on produce that doesn't jive properly when attempting to consume.

Below are the exact commands I'm using (env vars used for secrets)

```
# Consume
confluent kafka topic consume <topic> \
 --bootstrap $(KAFKA_BOOTSTRAP_SERVER) \
 --print-offset \
 --delimiter "|" \
 --value-format avro \
 --api-key $(KAFKA_USERNAME) \
 --api-secret $(KAFKA_PASSWORD) \
 --schema-registry-endpoint $(SCHEMA_REGISTRY_URL) \
 --schema-registry-api-key $(SCHEMA_REGISTRY_USER) \
 --schema-registry-api-secret $(SCHEMA_REGISTRY_PASSWORD)
 ```
 
 ```
# Produce
confluent kafka topic produce <topic> \
 --bootstrap $(KAFKA_BOOTSTRAP_SERVER) \ 
 --value-format avro \ 
 --schema "schemas/avro/avsc/value.avsc" \
 --key-format avro \
 --parse-key \
 --delimiter "|" \
 --key-schema "schemas/avro/avsc/key.avsc" \
 --api-key $(KAFKA_USERNAME) \
 --api-secret $(KAFKA_PASSWORD) \
 --schema-registry-endpoint $(SCHEMA_REGISTRY_URL) \
 --schema-registry-api-key $(SCHEMA_REGISTRY_USER) \
 --schema-registry-api-secret $(SCHEMA_REGISTRY_PASSWORD)
```

I've started digging into the code myself and think there is something going on in the `StoreSchemasReferences` (or related funcs) that store a reference to the schema, but not the schema itself.

**Comment by brianstrauch** [comment]
Thanks for reporting this bug! I was able to reproduce it by starting the consumer before the producer. The consumer doesn't have any knowledge of the producer's schema when this happens. We're working on a fix!
