### ISSUE TITLE
Error: the Confluent CLI requires Java version 1.8 or 1.11.

### ISSUE THREAD

**Issue by LauroSilveira** [confluentinc/cli#2612]
Hello, 
When I execute confluent local services start I am facing the error:
<p>
The local commands are intended for a single-node development environment only, NOT for production usage. See more: https://docs.confluent.io/current/cli/index.html
As of Confluent Platform 8.0, Java 8 will no longer be supported.

Using CONFLUENT_CURRENT: /var/folders/65/yd73hltj4_lc72d20ppndnsm0000gn/T/confluent.957436
ZooKeeper is [UP]
Kafka is [UP]
Error: the Confluent CLI requires Java version 1.8 or 1.11.
See https://docs.confluent.io/current/installation/versions-interoperability.html .
If you have multiple versions of Java installed, you may need to set JAVA_HOME to the version you want Confluent to use.
</p>

I am using the following Java aversion:
<p> 
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Homebrew (build 17.0.9+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.9+0, mixed mode, sharing)
</p>

My operational system is a MacBook Pro MacOS 13.6.4.
And at last I am downloaded conluent-7.6.0.
Please can you help me?

Kind regards

**Comment by brianstrauch** [comment]
Looks like we can remove that limitation. It's based on an `if` statement that was added 5 years ago: https://github.com/confluentinc/confluent-cli/blob/master/src/ccs/confluent.sh#L1035-L1041. I'll open a PR for this right away, thanks!

**Comment by LauroSilveira** [comment]
Good evening @brianstrauch, thank you for the response.

**Comment by javaHelper** [comment]
I am not clear on how to fix this issue? I'm getting the same issue reported here: https://stackoverflow.com/questions/78323808/unable-to-start-confluent-kafka-7-6-0-using-java-17?noredirect=1#comment138107334_78323808. Please guide
