### ISSUE TITLE
[Question] Producing Kafka message using Confluent CLI with headers

### ISSUE THREAD

**Issue by ashiishme** [confluentinc/cli#2768]
Hello Confluent team,

I am currently trying to emit the Kafka events that uses Avro. I am using Confluent CLI to produce the event messages. Everything is working as expected including the producing the message but I need to add the headers for the messages. I couldn't find a way to set it.

I have the Schema Registry setup for the avro and using the schema id when producing the message but I can only see the message data being processed. The headers are always empty.

Is there a way to define the headers from the Confluent CLI when producing the avro messages?

**Comment by brianstrauch** [comment]
Our docs (see [here](https://docs.confluent.io/confluent-cli/current/command-reference/kafka/topic/confluent_kafka_topic_produce.html)) state that:

> When using this command, you cannot modify the message header, and the message header will not be printed out.

We plan to add this functionality soon, and we'll update this issue when we have more information!

**Comment by ashiishme** [comment]
Hello @brianstrauch thank you for your response.

Is this the limitation only on the CLI package? I went through the code and found that internally the package uses the [confluent-kafka-go](https://github.com/confluentinc/confluent-kafka-go) and does it already supports the headers?

If yes, I can contribute to add this functionality or let me know if the feature is more dependent to multiple things.

**Comment by ashiishme** [comment]
I see it does support [headers](https://github.com/confluentinc/confluent-kafka-go/blob/b2b9f94bf85b60d915c7aad35d6302401e8fe849/kafka/message.go#L79), let me know if I can contribute. 🙂

**Comment by brianstrauch** [comment]
Yes, please feel free to open a PR!

**Comment by ashiishme** [comment]
#2775
