### ISSUE TITLE
README outdated - CLI 4.9 requires glibc 2.31 instead of 2.17 described in README

### ISSUE THREAD

**Issue by southwolf** [confluentinc/cli#2932]
![image](https://github.com/user-attachments/assets/49d77f5a-c60c-4450-a296-31cd96b17310)

When I tried to install CLI 4.9 I found it required glibc 2.31 instead of 2.17 described in README.

**Comment by sgagniere** [comment]
Hi, we have a PR to update the README.

However, the new GLIBC requirement should be 2.28, not 2.31. What Linux distribution are you using?

**Comment by sgagniere** [comment]
Hi @southwolf, the CLI should now only require GLIBC v2.28 when installing through yum as of CLI v4.10.0. The README will be updated to reflect this soon.

**Comment by southwolf** [comment]
Thanks @sgagniere  - I am using RHEL 8

**Comment by southwolf** [comment]
![image](https://github.com/user-attachments/assets/e24fba82-0a86-4462-a13d-02bcf71b7929)
It works now. Thanks @sgagniere
